name: mpflutter_template
description: A new MPFlutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter: "0.12.0"
  flutter_web_plugins: "0.12.0"
  mpcore: "0.12.0"
  mp_build_tools: "0.12.0"
dependency_overrides:
  flutter: "0.12.0"
  mpcore: "0.12.0"
  flutter_web_plugins: "0.12.0"