name: work_calendar
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mpflutter_core: ^2.1.2
  mpflutter_build_tools: ^2.1.2
  mpflutter_wechat_api: ^2.1.0
  mpflutter_wechat_mapview: ^0.0.3
  get: ^4.6.6
  shared_preferences: ^2.2.2
  lunar:
    path: ./lunar/lunar-flutter
  common_utils: ^2.1.0
  bruno: ^3.4.3

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
    - family: Noto Sans SC
      fonts:
        - asset: fonts/NotoSansSC-Regular.ttf
