name: work_calendar
description: Work calendar app
publish_to: "none"
version: 1.1.0+1
playbox:
  name: 模板工程
  description: 
  icon: school
  background: blue
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter: "1.3.0"
  flutter_web_plugins: "1.3.0"
  mpcore: "1.3.0"
  mp_build_tools: "1.3.0"
  get: ^4.3.9
  shared_preferences: ^2.0.8
  lunar:
    path: ./lunar/lunar-flutter
  common_utils: ^2.1.0
dependency_overrides:
  flutter: "1.3.0"
  mpcore: "1.3.0"
  flutter_web_plugins: "1.3.0"
