name: mpflutter_template
description: A new MPFlutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    git:
      url: https://github.com/mpflutter/mpflutter
      path: packages/flutter
      ref: 0.8.1
  mpcore:
    git:
      url: https://github.com/mpflutter/mpflutter
      path: packages/mpcore
      ref: 0.8.1
  mp_build_tools:
    git:
      url: https://github.com/mpflutter/mpflutter
      path: packages/mp_build_tools
      ref: 0.8.1
dependency_overrides:
  flutter:
    git:
      url: https://github.com/mpflutter/mpflutter
      path: packages/flutter
      ref: 0.8.1
  mpcore:
    git:
      url: https://github.com/mpflutter/mpflutter
      path: packages/mpcore
      ref: 0.8.1
  flutter_web_plugins:
    git:
      url: https://github.com/mpflutter/mpflutter
      path: packages/flutter_web_plugins
      ref: 0.8.1
